name: build-test

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'    
  push:    
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'
      
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: aminya/setup-node@arch
        with:
          node-version: 12.x
      - run: node --version
      - run: node __tests__/simple-test.js

  download:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: aminya/setup-node@arch
        with:
          node-version: 12.16.1
      - run: node --version
      - run: node __tests__/simple-test.js

  arch64:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12.16.1
        uses: aminya/setup-node@arch
        with:
          node-version: 12.16.1
          architecture: 'x64'
      - run: node --version
      - run: node __tests__/simple-test.js
  
  arch86:
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['12', '14.13.0', '12.16.1']
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: aminya/setup-node@arch
        with:
          node-version: ${{ matrix.node }}
          architecture: 'x86'
      - run: node --version
      - run: node __tests__/simple-test.js